### Get own lucky wants ###
GET http://localhost:3001/api/verified/mywants/lucky HTTP/1.1
Authorization: bearer *token*
content-type: application/json

#######

### Get own always wants ###
GET http://localhost:3001/api/verified/mywants/always HTTP/1.1
Authorization: bearer *token*
content-type: application/json

#######

### Get own arean wants ###
GET http://localhost:3001/api/verified/mywants/arean HTTP/1.1
Authorization: bearer *token*
content-type: application/json

#######

### Get own variant wants ###
GET http://localhost:3001/api/verified/mywants/variant HTTP/1.1
Authorization: bearer *token*
content-type: application/json

#######

### Get own costume wants ###
GET http://localhost:3001/api/verified/mywants/costume HTTP/1.1
Authorization: bearer *token*
content-type: application/json

#######

### Get own shiny wants ###
GET http://localhost:3001/api/verified/mywants/shiny HTTP/1.1
Authorization: bearer *token*
content-type: application/json