### Make new feature asking entry ###
PATCH http://localhost:3001/api/verified/password/change HTTP/1.1
Authorization: bearer *token*
content-type: application/json

    {
        "newPassword": "newPass",
        "oldPassword": "oldPass"
    }