### Get lucky wants list ###
GET http://localhost:3001/api/verified/wants HTTP/1.1
Authorization: bearer *token*
content-type: application/json

#######

### Get always wants list ###
GET http://localhost:3001/api/verified/wants/always HTTP/1.1
Authorization: bearer *token*
content-type: application/json

#######

### Get arean wants list ###
GET http://localhost:3001/api/verified/wants/arean HTTP/1.1
Authorization: bearer *token*
content-type: application/json

#######

### Change status of lucky want ###
PATCH http://localhost:3001/api/verified/wants/1 HTTP/1.1
Authorization: bearer *token*
content-type: application/json

{
    "pid": 1,
    "number": "001",
    "name": "First one",
    "img": "no_image",
    "want": true
}

#######

### Change status of always want ###
PATCH http://localhost:3001/api/verified/wants/always/1 HTTP/1.1
Authorization: bearer *token*
content-type: application/json

{
    "pid": 1,
    "number": "001",
    "name": "First one",
    "img": "no_image",
    "awid": 1,
    "awpid": 1,
    "uid": 1,
    "awant": true
}

#######

### Change status of arean want ###
PATCH http://localhost:3001/api/verified/wants/arean/1 HTTP/1.1
Authorization: bearer *token*
content-type: application/json

{
    "aid": 1,
    "apid": 1,
    "areanimg": "no_image",
    "pid": 1,
    "number": "001",
    "name": "First one (arean form)",
    "img": "no_arean_image",
    "arwant": true
}