### Get amount of Pokémons (rows on table) from database ###
GET http://localhost:3001/api/verified/pokemons/count HTTP/1.1
Authorization: bearer *token*
content-type: application/json

######

### Add new Pokémon to database ###
POST http://localhost:3001/api/verified/pokemons HTTP/1.1
Authorization: bearer *token*
content-type: application/json

{
    "number": "001",
    "name": "First one",
    "img": "no_image"
}