### Get list of Pokémons from database ###
GET http://localhost:3001/api/verified/seeds/pokemons HTTP/1.1
Authorization: bearer *token*
content-type: application/json

######

### Get list of Pokémons arean forms from database ###
GET http://localhost:3001/api/verified/seeds/pokemons/arean HTTP/1.1
Authorization: bearer *token*
content-type: application/json

######

### Get list of all lucky wants from database ###
GET http://localhost:3001/api/verified/seeds/wants HTTP/1.1
Authorization: bearer *token*
content-type: application/json

######

### Get list of all always wants from database ###
GET http://localhost:3001/api/verified/seeds/always HTTP/1.1
Authorization: bearer *token*
content-type: application/json

######

### Get list of all arean wants from database ###
GET http://localhost:3001/api/verified/seeds/arean HTTP/1.1
Authorization: bearer *token*
content-type: application/json